### ISSUE TITLE
Driver Transfers not working

### ISSUE THREAD

**Issue by TomLomas** [IUrreta/DatabaseEditor#286]
Whenever I try to move a driver I get this error appear in the top right. **_"Something went wrong. Please restart the tool"_**. 

No matter how many times I restart the tool I still seem to get the same issue when I drag a driver into a new team.

**Comment by IUrreta** [comment]
Share the save with me and the log.txt so I can take a look

**Comment by pperez0000** [comment]
I can't make the transfers

**Comment by timevagabond** [comment]
[log.txt](https://github.com/user-attachments/files/16533974/log.txt)

Attaching the log, not sure how to attach the save because it says file format is not accepted

**Comment by IUrreta** [comment]
Have you put values in the salary/sign bonus kind of inputs?

**Comment by timevagabond** [comment]
Oh, I see - because it auto-generates those values when you add a new contract via the Edit button, I had assumed it would do the same when you dragged to hire. But I see now that it doesn't. Understood!

There is also a second issue though, which you can see if you scroll to the bottom of this log.  It looks like there's an error thrown if a team has zero drivers, which I accidentally did to myself by not realizing some other things about how the contracts work.

[log.txt](https://github.com/user-attachments/files/16534222/log.txt)
