### ISSUE TITLE
Suggestion: package into executable

### ISSUE THREAD

**Issue by decline9** [IUrreta/DatabaseEditor#344]
Is there anything preventing this from being packaged into an `.exe` for Windows or `.app` for Mac? Don't get me wrong, having the source code is great for fellow devs, but I see a lot of people struggling with installing the dependencies to get the editor running. It'd solve like half of the open issues here.

**Comment by IUrreta** [comment]
I know, this is something I explored a year ago, in fact, I was able to pull it off and I had a version of the editor that installed itself and was all in a .exe. The problem is that Windows would flag it as a virus as it is not a certified signed executable and that would freak people out. Could I sign it? Probably, but it would cost money and I have very little idea of how that works

**Comment by decline9** [comment]
Understandable! I've never worked with electron, so I have no clue what I'm talking about here, but I guess porting this into a normal web app and hosting it somewhere is out of the question too? Does the editor use a lot of electron and node-specific features?
