### ISSUE TITLE
[BUG]Crash,when i sim

### ISSUE THREAD

**Issue by KaiN-31** [IUrreta/DatabaseEditor#347]
I changed the number of sprint races for several seasons, but this season suddenly started crashing. Every time I simulated Bahrain, it would crash. Please take a look, bro
[brokensave.zip](https://github.com/user-attachments/files/16621592/brokensave.zip)
![400b4d8a340ca9b53ed5f3470024dac](https://github.com/user-attachments/assets/8bf4d2f3-caff-4ba0-8fe2-dc7b7f268f8c)

**Comment by IUrreta** [comment]
I can’t do anything without the save

**Comment by KaiN-31** [comment]
[CrashSave.zip](https://github.com/user-attachments/files/16623968/CrashSave.zip)


> 没有保存，我什么也做不了

**Comment by KaiN-31** [comment]
> I can’t do anything without the save

zip

**Comment by KaiN-31** [comment]
[CrashF1M24Save.zip](https://github.com/user-attachments/files/16634790/CrashF1M24Save.zip)
just in case The save of last season is also included

**Comment by KaiN-31** [comment]
[log.txt](https://github.com/user-attachments/files/16643230/log.txt)

**Comment by KaiN-31** [comment]
bro can you help fix this ? can't play anymore

**Comment by IUrreta** [comment]
What do you want me to do? I do not dedicate my whole life to the editor, I have taken a look today because it's the earliest I have been able, and I don't see anything strange, sorry I can't help you more. Anyways, as I alwas say and is multiple times repeated accross the repo you should always do a backup before editing, so if you have one you should be good to go
