### ISSUE TITLE
[BUG] Game ignoring changes in edited saves

### ISSUE THREAD

**Issue by AR6137** [IUrreta/DatabaseEditor#380]
Hi, I downloaded the database editor on Windows 11 and everything seemed to work fine - I got it running, made changes to my saves, copied them and pasted in SaveGames file [C:\Users\[NAME]\AppData\Local\F1Manager24\Saved\SaveGames]. However, the game just ignores all of the modifications. Initially I thought that maybe Manager24 chose steam cloud saves over local files, but when I disabled and cleared the steam cloud, the saves still remained the same, even though I can see the changes as they where, when I return to the editor. None of them (Audi instead of Sauber, team logo, some stats and contracts etc.) makes it into the game and I've ran out of the ideas.

Has anyone had similar issue? Is there some solution that I'm missing?

**Comment by IUrreta** [comment]
I’m going to put a warning in the configuration modal because I see a lot of confusion over this topic. I guess I only warned about it when I introduces the features, so this is my bad. Team and logo changes are for the EDITOR AND ONLY THE EDITOR. They are visual changes just for the sake of not seeing “Sauber” if you have an Audi mod in your game. The other thungs that you say should not be happenening (contracts etc) and are most lokely due to a confusion over which save to copy and paste or which save file to load.

**Comment by AR6137** [comment]
Ok, my fault - while checking the changes I've made, I focused on those most visible, so I didn't look into the contract details that much. Anyway, editor works, it's great, thx for the effort and sorry for this misunderstanding. 
I guess I'll search for mods with proper brands now
